CREATE TABLE [dbo].[VaultHeritage] (
    [Id]                               NVARCHAR (450) NOT NULL,
    [VaultId]                         NVARCHAR (450) NOT NULL,
    [HeritageProtect]                  BIT            NULL,
    [MainResidence]                    BIT            NULL,
    [MainResidenceWording]             NVARCHAR (450) NULL,
    [MainResidenceAccuracy]            NVARCHAR (MAX) NULL,
    [SecondResidence]                  BIT            NULL,
    [SecondResidenceWording]           NVARCHAR (450) NULL,
    [SecondResidenceAccuracy]          NVARCHAR (MAX) NULL,
    [OtherRealEstate]                  BIT            NULL,
    [OtherRealEstateWording]           NVARCHAR (450) NULL,
    [OtherRealEstateAccuracy]          NVARCHAR (MAX) NULL,
    [BankAccount]                      BIT            NULL,
    [BankAccountWording]               NVARCHAR (450) NULL,
    [BankAccountAccuracy]              NVARCHAR (MAX) NULL,
    [LifeInsurance]                    BIT            NULL,
    [LifeInsuranceWording]             NVARCHAR (450) NULL,
    [LifeInsuranceAccuracy]            NVARCHAR (MAX) NULL,
    [UnitsSharesCompanies]             BIT            NULL,
    [UnitsSharesCompaniesWording]      NVARCHAR (450) NULL,
    [UnitsSharesCompaniesAccuracy]     NVARCHAR (MAX) NULL,
    [Copyright]                        BIT            NULL,
    [CopyrightWording]                 NVARCHAR (450) NULL,
    [CopyrightAccuracy]                NVARCHAR (MAX) NULL,
    [IndustrialProperty]               BIT            NULL,
    [IndustrialPropertyWording]        NVARCHAR (450) NULL,
    [IndustrialPropertyAccuracy]       NVARCHAR (MAX) NULL,
    [MotorVehicle]                     BIT            NULL,
    [MotorVehicleWording]              NVARCHAR (450) NULL,
    [MotorVehicleAccuracy]             NVARCHAR (MAX) NULL,
    [ValuablePersonalProperty]         BIT            NULL,
    [ValuablePersonalPropertyWording]  NVARCHAR (450) NULL,
    [ValuablePersonalPropertyAccuracy] NVARCHAR (MAX) NULL,
    [PortfolioOfShares]                BIT            NULL,
    [PortfolioOfSharesWording]         NVARCHAR (450) NULL,
    [PortfolioOfSharesAccuracy]        NVARCHAR (MAX) NULL,
    [Borrowing]                        BIT            NULL,
    [BorrowingWording]                 NVARCHAR (450) NULL,
    [BorrowingAccuracy]                NVARCHAR (MAX) NULL,
    [ShareWithMyFutureAgents]          BIT            NULL,
    [CompletedForm]                    BIT            NOT NULL,
    CONSTRAINT [PK_VaultHeritage] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_VaultHeritage_Vaults] FOREIGN KEY ([VaultId]) REFERENCES [dbo].[Vaults] ([Id])
);

