CREATE TABLE [dbo].[VaultPersonalInfos] (
    [Id]                    NVARCHAR (450) NOT NULL,
    [VaultId]              NVARCHAR (450) NOT NULL,
    [FrenchMotherTongue]    BIT            NULL,
    [OtherLanguage]         NVARCHAR (128) NULL,
    [UnderstandFrench]      NVARCHAR (128) NULL,
    [SpeakFrench]           NVARCHAR (128) NULL,
    [ProfessionalSituation] NVARCHAR (128) NULL,
    [LevelOfStudy]          NVARCHAR (128) NULL,
    [LevelOfStudyDetails]   NVARCHAR (MAX) NULL,
    [Job]                   NVARCHAR (128) NULL,
    [JobDetails]            NVARCHAR (MAX) NULL,
    [CV]                    BIT            NULL,
    [ProtectiveSupervision] NVARCHAR (128) NULL,
    [LivingEnvironment]     NVARCHAR (128) NULL,
    [TypeOfHousing]         NVARCHAR (128) NULL,
    [HousingLaw]            NVARCHAR (128) NULL,
    [CoOwnership]           BIT            NULL,
    [OngoingLitigation]     BIT            NULL,
    [Nblitigations]         INT            NULL,
    [NbLawyerFirms]         INT            NULL,
    [CanShareInfos]         BIT            NULL,
    [CompletedForm]         BIT            NOT NULL,
    [PrecisionHousing] NVARCHAR(450) NULL, 
    [PrecisionLitigation] NVARCHAR(450) NULL, 
    CONSTRAINT [PK_VaultPersonalInfos] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_VaultPersonalInfos_Vaults] FOREIGN KEY ([VaultId]) REFERENCES [dbo].[Vaults] ([Id])
);

